language: python
python:
- '2.7'
sudo: required
services:
- docker
notifications:
  email:
    recipients:
    - tgu@anl.gov
    on_success: never
    on_failure: always
env:
  global:
    secure: K5n332wVgKI/TbsnqjP8YQd9OM/ONPKP1ftOAzTHyv977Yc12jJUPHoAfPhP8pYm4doPiQ2V9PdPHrzEWXmgXweIY7SDBrEMe9PrKaH8GDJW8nKzpFfz/vKYqZQ5jJFVBygy0QJYlmgsGGTIIm7lGkS70rbiuAfx3y/dD8qYSBhZIwuI7sRs8/wIpMJtD6eymmIlPIHHjjcSBSHB5L++nXsCI7cfksS2rumyxX86XtSvf/IKAHP44vQ1tWgTKtR/8pekTU02XSYHpytPast6LUtDhpQGzxc/UcNGr+nb+6YHwl9UOz6HApZv+Di3gcN6bV6swnIG73FesF/DJVI/bD+fRM4DdjhPN1FQtfz3BWxTrcH7ujS+PJ+zEQRXJJ0vA9qcq9ExDYWCnh+3weMEeWnLkZb0L2VlhSQ7KCnsXvsiQ1VOmHoDymj/bUxZq8JRlHN+Ua+H4gQduUL658pGKs0QazL2qZ/U0cYQ/YsTESl1ETulSobsCpnVDvE1sydO/WJ21X1WwkxFxtNIJFwd9n8I4nHI4RVyEIiRGqy0ZV1i88wdNP9Y08pjElUbHv89n6xdJqgvAqjsUm0GbkNvG72U3LoIPXKGfuqmNe/lvmv5ivDrKhULSrzKy8Ixg4FyIQJ4NeSYO9Hn7KNpMftBDJyQMzU7JVMs689DKsd0/Kw=
branches:
  only:
  - master
before_install:
- docker version
- python --version
- javac -version
- java -version
install:
- pip install coveralls
- git clone https://github.com/kbase/jars
- git clone https://github.com/kbase/kb_sdk
- cd kb_sdk
- make
- make sdkbase
- docker images
- export PATH=$(pwd)/bin:$PATH
- cd ../
- git clone https://github.com/kbaseapps/kb_stringtie.git
- cd kb_stringtie
- kb-sdk test || true
- sed -i "s/test_token=/test_token=$TEST_TOKEN/" test_local/test.cfg
# - sed -i 's\https://appdev.kbase.us/services\https://ci.kbase.us/services\' test_local/test.cfg
# - sed -i 's\https://appdev.kbase.us/services/auth/api/legacy/KBase/Sessions/Login\https://ci.kbase.us/services/auth/api/legacy/KBase/Sessions/Login\'
#   test_local/test.cfg
- sed -i 's/$(id -u)/0:0/' test_local/run_tests.sh
- pwd=$(pwd)
- echo "#!/bin/bash" >> test_local/run_subjob.sh
- echo -e "$pwd/test_local/run_docker.sh run --rm --user 0:0 -v $pwd/test_local/subjobs/\$1/workdir:/kb/module/work
  -v $pwd/test_local/workdir/tmp:/kb/module/work/tmp \$4 -e \"SDK_CALLBACK_URL=\$3\"
  \$2 async" >> test_local/run_subjob.sh
- cat test_local/run_subjob.sh
script:
- kb-sdk test
after_success:
- cp test_local/workdir/.coverage .
- sudo mkdir -p /kb/module/lib/
- sudo cp -R test_local/workdir/kb/module/lib/kb_stringtie /kb/module/lib/
- pwd
- ls -l /kb/module/lib/kb_stringtie
- cat .coverage
- coverage report -m
- coveralls
